# Generated by Django 5.2.16 on 2026-09-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviews_options_alter_reviews_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='admin_note',
            field=models.CharField(blank=True, verbose_name='ответ админа'),
        ),
    ]
