# Generated by Django 5.2.16 on 2026-08-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='деф', max_length=50, verbose_name='Заголовок (для юрл строки)'),
            preserve_default=False,
        ),
    ]
