# Generated by Django 5.2.16 on 2026-09-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='booking/', verbose_name='аватарка')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('number', models.CharField(max_length=15, verbose_name='номер')),
                ('adres', models.CharField(max_length=50, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
    ]
