# Generated by Django 5.2.16 on 2026-09-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('link', models.CharField(max_length=500, verbose_name='ссылка')),
                ('icon', models.CharField(max_length=100, verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'соцсеть',
                'verbose_name_plural': 'соцсети',
            },
        ),
        migrations.CreateModel(
            name='BookingNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='фио теренера')),
                ('number', models.CharField(verbose_name='номер тренера')),
            ],
            options={
                'verbose_name': 'номер тренера',
                'verbose_name_plural': 'номера тренеров',
            },
        ),
    ]
