# Generated by Django 5.2.16 on 2026-09-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingmedia_bookingnumbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'главный контакт', 'verbose_name_plural': 'главный контакт'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='adres',
            new_name='adress',
        ),
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.CharField(max_length=20, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='bookingnumbers',
            name='name',
            field=models.CharField(max_length=50, verbose_name='фио теренера'),
        ),
        migrations.AlterField(
            model_name='bookingnumbers',
            name='number',
            field=models.CharField(max_length=50, verbose_name='номер тренера'),
        ),
    ]
