# Generated by Django 5.2.16 on 2026-08-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО тренера')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='trainers/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
