# Generated by Django 5.2.16 on 2026-08-06 10:00

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50, verbose_name='должность')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='номер')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
