# Generated by Django 5.2.16 on 2026-08-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gym_gallery', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Фотография зала',
                'verbose_name_plural': 'Фотографии зала',
            },
        ),
    ]
