# Generated by Django 5.2.16 on 2026-08-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gymgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('url_name', models.CharField(max_length=50, verbose_name='ссылка')),
                ('icon', models.CharField(max_length=50, verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'Элемент навигации',
                'verbose_name_plural': 'Элементы навигации',
            },
        ),
    ]
