# Generated by Django 5.2.16 on 2026-08-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_navigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('url_name', models.CharField(max_length=50, verbose_name='ссылка')),
                ('icon', models.CharField(max_length=50, verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'Иконка соцсети',
                'verbose_name_plural': 'Иконки соцсетей',
            },
        ),
    ]
