# Generated by Django 5.2.16 on 2026-08-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_socialmediaicons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigation',
        ),
        migrations.DeleteModel(
            name='SocialMediaIcons',
        ),
    ]
