# Generated by Django 5.2.16 on 2026-09-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_navigation_delete_socialmediaicons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymgallery',
            name='photo',
            field=models.ImageField(upload_to='gym_gallery/', verbose_name='фото'),
        ),
    ]
