# Generated by Django 5.2.16 on 2026-08-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='цена в месяц')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_code/', verbose_name='qr код')),
            ],
            options={
                'verbose_name': 'цена и qr код',
                'verbose_name_plural': 'цена и qr код',
            },
        ),
    ]
