# Generated by Django 5.2.16 on 2026-09-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='qr_code',
            field=models.ImageField(upload_to='qr_code/', verbose_name='qr код'),
        ),
    ]
