# Generated by Django 5.2.16 on 2026-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('monday', models.CharField(default='---', max_length=11, verbose_name='понедельник')),
                ('tuesday', models.CharField(default='---', max_length=11, verbose_name='вторник')),
                ('wednesday', models.CharField(default='---', max_length=11, verbose_name='среда')),
                ('thursday', models.CharField(default='---', max_length=11, verbose_name='четверг')),
                ('friday', models.CharField(default='---', max_length=11, verbose_name='пятница')),
                ('saturday', models.CharField(default='---', max_length=11, verbose_name='суббота')),
            ],
        ),
    ]
