# Generated by Django 5.2.16 on 2026-08-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'расписание', 'verbose_name_plural': 'расписания'},
        ),
    ]
